# Generated by Django 5.0.6 on 2024-06-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_availability',
            field=models.BooleanField(null=True, verbose_name=True),
        ),
    ]
