# Generated by Django 5.0.6 on 2024-06-30 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager', '0002_room_room_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_manager.room')),
            ],
            options={
                'unique_together': {('date', 'room_id')},
            },
        ),
    ]
