# Generated by Django 5.0.6 on 2024-07-02 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager', '0003_roomreservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_availability',
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking_manager.room'),
        ),
    ]
